apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-demo-001
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-demo-001
  template:
    metadata:
      labels:
        app: java-demo-001
    spec:
      containers:
      - name: java-demo-001
        image: registry.cn-shanghai.aliyuncs.com/qinyujia-test/java-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: java-demo-001
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: java-demo-001
  selector:
    app: java-demo-001
  type: NodePort
